config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users, skip: [:passwords], :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'filter' => 'searches#filter', as: 'filter'
  get 'user_search' =>'users#search', as: 'user_search'
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :favorites
    end
  end
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
  end
  resources :makers, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :goods, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト',email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search,word)
    User.where("name LIKE?", "%#{word}%")
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :only_admin, only: [:edit]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def only_admin
    unless current_user.admin
      redirect_to user_path(current_user)
     end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only:[:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to items_path, notice: 'ゲストログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
         redirect_to new_user_registration_path
      end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit, :withdrawal, :favorites]
  before_action :ensure_user, only: [:edit, :update, :favorites]
  before_action :only_admin, only: [:index, :search]
  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    reviews = Review.where(user_id: @user)
    @reviews = Kaminari.paginate_array(reviews).page(params[:page]).per(12)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
       flash[:notice] = "プロフィールを編集しました。"
       redirect_to user_path(user)
    else
       user = User.find(params[:id])
       flash[:alert] = "編集に失敗しました。"
       render 'edit'
    end
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:item_id)
    @favorite_items = Item.find(favorites)
    @favorite_items = Kaminari.paginate_array(@favorite_items).page(params[:page]).per(15)
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会しました。"
    redirect_to root_path
  end

  def search
    @users = User.looks(params[:search], params[:word])
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(20)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :is_deleted)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "ゲスト"
      redirect_to user_path(current_user), alert: 'ゲストユーザーには使用できない機能です。'
    end
  end

  def ensure_user
    @user = User.find(params[:id])
    unless (@user == current_user) || current_user.admin?
      redirect_to user_path(current_user)
    end
  end

  def only_admin
    unless current_user.admin
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_b_btn.html.erb
<% if item.favorited_by?(current_user) %>
  <%= link_to item_favorites_path(item), method: :delete, remote: true, class: 'text-ratyyellow xs:text-xs sm:text-base' do %>
    <i class="fas fa-bookmark"></i>
  <% end %>
<% else %>
  <%= link_to item_favorites_path(item), method: :post, remote: true, class: 'text-gray-400 hover:text-ratyyellow xs:text-xs sm:text-base' do %>
    <i class="far fa-bookmark"></i>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<div class="flex w-full flex-wrap gap-1">
  <% @users.each do |user| %>
    <div class="border p-5 bg-twibg border-t-8 border-teal300">
      <div class="flex justify-center w-52">
        <%= link_to user_path(user), class: 'text-pink-200 font-semibold mr-2 mb-2 hover:text-pink-400' do %>
          <%= user.name %>
        <% end %>
        <% if user.is_deleted == true %>
          <p class="text-red-400 flex">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          </p>
        <% else %>
          <p class="text-teal300 flex">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" /></svg>
          </p>
        <% end %>
      </div>
      <%= link_to user_path(user) do %>
        <%= image_tag user.get_profile_image(80,80), class: 'rounded-full hover:opacity-75 bg-white mx-auto' %>
      <% end %>
      <p class="text-gray-200 mt-2"><%= user.email %></p>
    </div>
  <% end %>
</div>
<div class="text-center mt-10"><%= render '/users/search' %></div>

app/views/users/_modal.html.erb
<div class="modal js-modal hidden h-screen fixed top-0 w-full" id="modal_<%= review.id %>">
  <div class="modal__bg js-modal-close bg-gray-100 opacity-75 h-screen absolute w-full"></div>
  <div class="modal__content text-gray-400 bg-cream3 left-2/4 px-20 pt-14 relative absolute top-1/2 transform -translate-x-2/4 -translate-y-2/4 xs:w-11/12 sm:w-3/5 rounded-md shadow-lg">
    <p class="break-words xs:text-xs sm:text-base xs:w-11/12 sm:w-auto text-black"><%= review.comment %></p>
    <div id="good_btn<%= review.id %>" class="mt-7">
      <%= render 'items/good_btn', review: review %>
    </div>
    <button class="js-modal-close mt-10">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 absolute top-6 right-6 hover:opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
    </button>
  </div>
</div>

app/views/users/_reviews.html.erb
<div class="w-full flex flex-wrap mx-auto gap-3">
  <% reviews.each do |review| %>
    <div class="mx-auto">
      <div class="text-center bg-twibg rounded-md pb-1 xs:w-40 md:w-60">
        <%= link_to item_path(review.item.id) do %>
          <%= image_tag review.item.image.variant(resize: "600x600^", gravity: "center", crop: "600x600+0+0").processed, class: 'xs:w-40 md:w-60 xs:mx-auto rounded-md hover:opacity-75' %>
        <% end %>
        <% if current_user.admin || current_user == review.user %>
          <div class="text-right pr-1 pt-2">
            <%= link_to edit_item_review_path(review.item.id, review), class: 'text-gray-400' do %>
              <i class="fas fa-edit hover:opacity-75"></i>
            <% end %>
          </div>
        <% else %>
          <div class="mt-5"></div>
        <% end %>
          <%= link_to item_path(review.item.id), class: 'font-bold break-words text-center pt-3 text-gray-300 hover:opacity-75' do %>
            <%= review.item.name %>
          <% end %>
        <p class="flex mt-3 justify-center" id="star2<%= review.id %>"></p>
        <p class="mb-2 text-gray-400 text-center mt-3"><%= review.rate %></p>
        <p class="xs:text-xs md:text-base text-gray-400 mx-auto px-5 mb-3 line-clamp-3">
          <a class="js-modal-open break-words hover:text-gray-200" data-target="#modal_<%= review.id %>" href=""><%= review.comment %></a>
        </p>
        <script>
          $('#star2<%= review.id %>').empty();
          $('#star2<%= review.id %>').raty({
            size      : 36,
            starOff   : '<%= asset_path('star-off.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            half      : false,
            readOnly: true,
            score: <%= review.rate %>,
            });
        </script>
      </div>
    </div>
    <%= render '/users/modal', review: review %>
  <% end %>
</div>

<script>
  $(function(){
   $('.js-modal-open').on('click',function(){
     $($(this).data('target')).fadeIn();
     return false;
   });
   $('.js-modal-close').on('click',function(){
     $('.js-modal').fadeOut();
     return false;
   });
  });
</script>

app/views/users/_search.html.erb
<div>
  <%= form_with url: user_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder: "name", class: 'xs:w-60 md:w-3/5 lg:w-1/2 xl:w-1/3 p-2 bg-twibg text-gray-200 text-sm focus:ring-4 focus:ring-purple-400 duration-300 rounded-md placeholder-gray-400 placeholder-opacity-50' %>
    <%= f.button :type => "submit", class: 'text-teal300 h-9 w-9 rounded-full focus:ring-4 focus:ring-teal300 ml-3' do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container mt-5 mx-auto">
  <div class="text-center text-gray-400 h-1/2">
    <%= form_with model: @user, local: true do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'p-2 bg-gray-700 text-gray-200 text-sm focus:ring-4 focus:ring-purple-400 duration-300 rounded-md mb-5' %><br>
      <%= f.label :profileimage %><br>
      <div class="h-full"><%= image_tag @user.profile_image.variant(resize: "400x400^",gravity: "center", crop: "400x400+0+0").processed, class: 'rounded-full bg-white mx-auto my-5' %></div>
      <div class="mt-10 mb-5"><%= f.file_field :profile_image, accept: "image/*" %></div>
      <% if current_user.admin? %>
        <span>
          <%= f.label :is_deleted, "有効", value: false %>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "退会", value: true %>
          <%= f.radio_button :is_deleted, true %>
        </span><br>
      <% end %>
      <%= button_tag(type: "submit") do %>
        <div class="<%= btn %> my-3">変更</div>
      <% end %>
    <% end %>
    <%= link_to withdrawal_path(@user),method: :patch, "data-confirm" => "退会しますか？" do %>
      <button class="<%= btnd %> mt-3">退会する</button>
     <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container mx-auto sm:mt-5 sm:mb-5">
  <div class="favorite-list favorite_scroll my-10">
    <div class="flex flex-wrap w-full gap-10">
      <% @favorite_items.each do |item| %>
        <div class="bg-twibg shadow-lg rounded-md xs:w-32 lg:w-1/6">
          <%= link_to item_path(item), data: {"turbolinks" => false} do %>
            <%= image_tag item.image.variant(resize: "600x600^", gravity: "center", crop: "600x600+0+0").processed, class: 'hover:opacity-75 rounded' %>
          <% end %>
          <div class="py-4 text-sm text-center mt-2 relative">
            <%= link_to item_path(item), data: {"turbolinks" => false} do %>
             <span class="font-bold text-gray-300 hover:opacity-75 xs:text-xs sm:text-base md:px-2 lg:px-0"><%= item.name %></span>
            <% end %>
            <% if current_user == @user %>
              <span class="absolute top-0 right-1 mb-1" id="b_btn<%= item.id %>">
                <%= render 'b_btn',item: item %>
              </span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="hidden"><%= paginate @favorite_items %></div>
  </div>
</div>

<script>
  $(window).on('scroll', function() {
    scrollHeight = $(document).height();
    scrollPosition = $(window).height() + $(window).scrollTop();
    if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
      $('.favorite_scroll').jscroll({
        loadingHtml: '<div class="flex items-center justify-center pt-5"><svg width="24px" height="24px" class="animate-spin viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path opacity="0.2" fill-rule="evenodd" clip-rule="evenodd" d="M12 19C15.866 19 19 15.866 19 12C19 8.13401 15.866 5 12 5C8.13401 5 5 8.13401 5 12C5 15.866 8.13401 19 12 19ZM12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" fill="pink"/><path d="M2 12C2 6.47715 6.47715 2 12 2V5C8.13401 5 5 8.13401 5 12H2Z" fill="pink"/></svg></div>',
        contentSelector: '.favorite-list',
        nextSelector: 'span.next:last a'
      });
    }
  });
</script>

app/views/users/index.html.erb
<div class="container mt-5 mx-auto text-center">
  <%= render '/users/index', users: @users %>
  <div class="pt-10 mt-10 mx-auto text-lg"><%= paginate @users %></div>
</div>

app/views/users/search.html.erb
<div class="container mt-5 mx-auto text-center">
  <%= render '/users/index', users: @users %>
  <div class="pt-10 mt-10 mx-auto text-lg"><%= paginate @users %></div>
</div>

app/views/users/show.html.erb
<div class="container mx-auto">
  <div class="mt-10 mb-10">
    <div class="lg:w-1/3 mx-auto my-5">
      <%= image_tag @user.get_profile_image(600,600), class: 'rounded-full xs:w-40 sm:w-1/4 lg:w-1/2 mx-auto bg-white' %>
        <p class="text-center text-pink-200 mt-3 text-lg font-bold"><%= @user.name %></p>
        <div class="text-center">
          <% if (current_user == @user || current_user.admin?) && current_user.name != "ゲスト" %>
            <div class="my-5">
              <%= link_to edit_user_path(@user), class: 'p-3 px-4 bg-transparent rounded-3xl text-gray-400 hover:bg-twibg xs:text-xs md:text-base' do %>
                <i class="far fa-address-card"></i> プロフィール編集
              <% end %>
            </div>
            <div class="mt-5">
              <%= link_to favorites_user_path(@user), class: 'p-3 px-4 bg-transparent rounded-3xl text-gray-400 hover:bg-twibg xs:text-xs md:text-base' do %>
                <i class="far fa-bookmark"></i> ブックマーク
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>
<div class="">
  <%= render '/users/reviews', reviews: @reviews %>
  <div class="py-10 text-lg"><%= paginate @reviews %></div>
</div>