config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users, skip: [:passwords], :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'filter' => 'searches#filter', as: 'filter'
  get 'user_search' =>'users#search', as: 'user_search'
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :favorites
    end
  end
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
  end
  resources :makers, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :maker
  belongs_to :category

  attr_accessor :average
  attr_accessor :amount


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def review_rate_average
    if reviews
      reviews.average(:rate).to_f.round(1)
    else
      0.0
    end
  end

  def review_amount
    if reviews
      reviews.count
    else
      0.0
    end
  end

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
    .category_like(search_params[:category_ids])
    .maker_like(search_params[:maker_ids])
  end

  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :category_like, -> (category) { where(category: category) if category.present? }
  scope :maker_like, -> (maker) { where(maker: maker) if maker.present? }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :only_admin, except: [:index, :show]

  def new
    @item = Item.new
    @category = Category.new
    @categories = Category.all
    @maker = Maker.new
    @makers = Maker.all
  end

  def create
    item = Item.new(item_params)
    if item.save
      redirect_to request.referer, notice: "追加しました。"
    else
      redirect_to request.referer, alert: "追加に失敗しました。"
    end
  end

  def index
    if Rails.env.development? || Rails.env.test?
      @items = Item.order("RANDOM()").limit(12)
    else
      @items = Item.order("RAND()").limit(12)
    end
  end

  def show
    @item = Item.find(params[:id])
    @review = Review.new
    item_reviews = Review.where(item_id: @item.id)
    @review_count = item_reviews.count
    @average = item_reviews.average(:rate)
    if params[:rate] == "1"
      item_reviews = Review.where(item_id: @item.id, rate: 1)
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    elsif params[:rate] == "2"
      item_reviews = Review.where(item_id: @item.id, rate: 2)
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    elsif params[:rate] == "3"
      item_reviews = Review.where(item_id: @item.id, rate: 3)
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    elsif params[:rate] == "4"
      item_reviews = Review.where(item_id: @item.id, rate: 4)
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    elsif params[:rate] == "5"
      item_reviews = Review.where(item_id: @item.id, rate: 5)
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    else
      @reviews = Kaminari.paginate_array(item_reviews).page(params[:page]).per(20)
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to item_path(item), notice: "変更しました。"
    else
      redirect_to request.referer, alert: "変更に失敗しました。"
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path, notice: "削除しました。"
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :category_id, :maker_id)
  end

  def only_admin
    unless current_user.admin
      redirect_to user_path(current_user)
    end
  end

  def item_search_params
    params.fetch(:search, {}).permit(:category_id, :maker_id, category_ids: [], maker_ids: [])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_average.html.erb
 <div class="flex justify-center items-center">
    <span class="flex justify-center my-3 mr-1" id="star3"></span>
    <p class="text-gray-300 opacity-75 pl-3"><%= average.to_f.round(1) %></p>
 </div>
<div class="text-gray-300 opacity-50">
  <i class="far fa-comment"></i>
  <%= review_count %>
</div>
<script>
  $('#star3').empty();
  $('#star3').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: <%= average || 0 %>,
  });
</script>

app/views/items/_favorite_btn.html.erb
<% if item.favorited_by?(current_user) %>
  <%= link_to item_favorites_path(item), method: :delete, remote: true, class: 'text-ratyyellow absolute top-2 right-3 xs:text-sm sm:text-xl' do %>
    <i class="fas fa-bookmark"></i>
  <% end %>
<% else %>
  <%= link_to item_favorites_path(item), method: :post, remote: true, class: ' absolute top-2 right-3 xs:text-sm sm:text-xl' do %>
    <i class="far fa-bookmark text-gray-400 hover:text-ratyyellow"></i>
  <% end %>
<% end %>

app/views/items/_form.html.erb
<div class="rounded-md xs:pb-3 pt-5 bg-twibg xs:w-72 lg:w-96 h-full" id="review_form">
  <div class="my-auto">
    <%= form_with model: [item,review], local: true do |f| %>
      <div class="text-center p-3"><%= f.text_area :comment, placeholder: "レビュー", class: 'border border-gray-600 shadow-inner xs:w-4/5 sm:w-4/5 xs:h-40 md:h-60 p-2 bg-twibg text-gray-200 text-sm focus:ring-4 focus:ring-purple-400 duration-300 rounded-md placeholder-gray-400 placeholder-opacity-50' %></div>
      <div id="star1" class="flex justify-center lg:mt-3">
        <%= f.label :rate,'評価 '%>
      </div>
      <script>
      $('#star1').empty();
        $('#star1').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn: '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'review[rate]',
          half: false,
        });
      </script>
      <div class="text-center mt-5 w-full">
        <%= button_tag(type: "submit", class: 'w-2/3') do %>
          <div class="<%= btn %> lg:mt-3"><i class="fas fa-paper-plane"></i></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_form_search.html.erb
<div>
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, required: true, placeholder: "キーワード", class: 'w-40 p-2 bg-gray-700 text-gray-200 text-sm focus:ring-4 focus:ring-purple-400 duration-300 rounded-md placeholder-gray-400' %>
    <%= f.button :type => "submit", class: 'text-pink-200 bg-gray-700  h-9 w-9 rounded-full focus:ring-2 focus:ring-pink-200 ml-3' do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/items/_good_btn.html.erb
<% if review.good_by?(current_user)%>
  <p class="">
    <%= link_to item_review_goods_path(review,review.item), method: :delete, remote: true, class: 'text-ratyyellow' do %>
      <i class="fas fa-thumbs-up xs:mr-0 sm:mr-1"></i><%= review.goods.count %>
    <% end %>
  </p>
<% else %>
  <div class="">
    <%= link_to item_review_goods_path(review,review.item), method: :post, remote: true, class: 'text-gray-400 hover:text-ratyyellow' do %>
      <i class="far fa-thumbs-up xs:mr-0 sm:mr-1"></i><%= review.goods.count %>
    <% end %>
  </div>
<% end %>

app/views/items/_modal.html.erb
<div class="modal js-modal hidden h-screen fixed top-0 w-full" id="modal_<%= review.id %>">
  <div class="modal__bg js-modal-close bg-gray-100 opacity-75 h-screen absolute w-full"></div>
  <div class="modal__content text-gray-400 bg-cream3 left-2/4 px-20 pt-14 absolute top-1/2 transform -translate-x-2/4 -translate-y-2/4 xs:w-11/12 sm:w-3/5 rounded-md shadow-lg">
    <p class="break-words xs:text-xs sm:text-base xs:w-11/12 sm:w-auto text-black"><%= review.comment %></p>
    <button class="js-modal-close mt-10">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 absolute top-6 right-6 hover:opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
    </button>
  </div>
</div>

app/views/items/_reviews.html.erb
<% reviews.each do |review| %>
  <div class="sm:flex justify-around bg-twibg shadow-md mb-3 rounded-md xs:p-2 sm:p-5 xs:h-auto sm:h-32 xs:w-11/12 sm:w-4/5 md:w-11/12 lg:w-5/6 xl:w-3/6 mx-auto">
    <div class="">
      <%= link_to user_path(review.user) do %>
        <%= image_tag review.user.get_profile_image(700,700), class: 'xs:w-12 md:w-16 rounded-full hover:opacity-75 bg-white xs:mx-auto sm:mx-0' %>
      <% end %>
      <p class="font-bold mt-2 whitespace-nowrap text-center text-gray-400"><%= review.user.name %></p>
    </div>
    <div class="mt-3">
      <span class="flex pl-5 justify-center star2<%= review.id %>"></span>
    </div>
    <p class="text-gray-400 sm:mt-2 md:ml-2 sm:px-3 xl:px-10 text-center"><%= review.rate %></p>
    <p class="xs:w-auto xs:mt-2 sm:mt-0 sm:w-60 md:w-96 text-sm text-gray-400 line-clamp-4 xs:h-20 my-auto md:my-0 text-center">
       <a class="js-modal-open px-3 hover:text-gray-200" data-target="#modal_<%= review.id %>" href=""><%= review.comment %></a>
    </p>
    <div class="h-full w-auto text-right sm:text-right flex flex-col xs:pr-2 sm:pr-0">
      <% if current_user.admin || current_user == review.user %>
        <%= link_to edit_item_review_path(review.item.id, review), class: 'text-gray-400' do %>
          <i class="fas fa-edit hover:opacity-75"></i>
        <% end %>
      <% end %>
      <div id="good_btn<%= review.id %>" class="mt-auto">
        <%= render '/items/good_btn', review: review %>
      </div>
    </div>
  </div>
  <script>
    $('.star2<%= review.id %>').empty();
    $('.star2<%= review.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      half      : false,
      readOnly: true,
      score: <%= review.rate %>,
    });
    $(function(){
     $('.js-modal-open').on('click',function(){
       $($(this).data('target')).fadeIn();
       return false;
     });
     $('.js-modal-close').on('click',function(){
       $('.js-modal').fadeOut();
       return false;
     });
    });
  </script>

  <div class="w-full"><%= render '/items/modal', review: review %></div>
<% end %>

app/views/items/edit.html.erb
<div class="container mt-5 mx-auto">
  <div class="text-center text-gray-400">
    <%= form_with model: @item, local: true do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'bg-twibg text-gray-200 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300 mx-auto w-1/3 block mt-1 xs:w-4/5 sm:w-1/3' %><br>
      <%= f.label :image %><br>
      <%= image_tag @item.image.variant(resize: "300x300^",gravity: "center", crop: "300x300+0+0").processed, class: 'mx-auto mt-3' %>
      <div class="mt-10"><%= f.file_field :image, accept: "image/*" %></div>
        <%= button_tag(type: "submit") do %>
          <div class="<%= btn %> mt-9 mx-3">変更</div>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to item_path(@item),method: :delete, "data-confirm" => "本当に削除しますか？" do %>
            <button class="<%= btnd %> mx-3 mt-6">削除</button>
           <% end %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div id="cga" class="relative overflow-hidden bg-no-repeat bg-cover bg-center h-screen">
  <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"style="background-color: rgba(0, 0, 0, 0.75)">
    <div class="flex justify-center h-full">
      <div class="text-center text-white px-6 md:px-12">
        <h1 class="text-5xl font-black mt-52 mt-0 mb-8">addevice</h1>
        <h3 class="text-xl font-bold">device + advice</h3>
      </div>
    </div>
</div>

<div class="flex absolute xs:bottom-10 sm:bottom-20 overflow-hidden">
  <div class="slidebox flex items-center overflow-hidden slidestop" style="height: 400px;">
    <ul class="slideshow">
      <% @items.each do |item| %>
        <div class="p-0.5 bg-gradient-to-tr from-purple-800 to-pink-800 rounded-lg transform hover:scale-110 hover:-translate-y-5 duration-500" id="marginclass">
          <%= link_to item_path(item) do %>
            <li class="content"><%= image_tag item.image.variant(resize: "700x700^", gravity: "center", crop: "700x700+0+0").processed, class: 'rounded-lg  shadow-md hover:opacity-75' %></li>
          <% end %>
        </div>
      <% end %>
    </ul>
    <ul class="slideshow">
      <% @items.each do |item| %>
        <div class="p-0.5 bg-gradient-to-tr from-purple-800 to-pink-800 rounded-lg transform hover:scale-110 hover:-translate-y-5 duration-500" id="marginclass">
          <%= link_to item_path(item) do %>
            <li class="content"><%= image_tag item.image.variant(resize: "700x700^", gravity: "center", crop: "700x700+0+0").processed, class: 'rounded-lg shadow-md hover:opacity-75' %></li>
          <% end %>
        </div>
      <% end %>
    </ul>
    <ul class="slideshow">
      <% @items.each do |item| %>
        <div class="p-0.5 bg-gradient-to-tr from-purple-800 to-pink-800 rounded-lg transform hover:scale-110 hover:-translate-y-5 duration-500" id="marginclass">
          <%= link_to item_path(item) do %>
            <li class="content"><%= image_tag item.image.variant(resize: "700x700^", gravity: "center", crop: "700x700+0+0").processed, class: 'rounded-lg shadow-md hover:opacity-75' %></li>
          <% end %>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/new.html.erb
<div class="container mt-10 mb-5 mx-auto">
  <%= render 'layouts/error', obj: @item %>
  <div class="flex flex-wrap text-gray-400 justify-around">
    <div class="h-full py-5 pl-5 bg-twibg rounded-md shadow-md mx-3 xs:mb-5 md:mb-0 xs:w-full sm:w-auto">
        <%= form_with model: @item, local: true do |f| %>
          <span class="text-pink-200 flex">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mt-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
            <%= f.text_field :name, placeholder: '製品名', class: 'w-1/2 bg-gray-700 text-gray-400 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300 ml-2 placeholder-opacity-30 placeholder-white' %><br>
          </span>
          <%= f.file_field :image, class: 'my-10' %><br>
          <%= f.collection_select(:maker_id, @makers, :id, :name, {prompt: "メーカー"}, {class: 'border text-black p-1 rounded'}) %><br>
          <%= f.collection_select(:category_id, @categories, :id, :name, {prompt: "カテゴリー"}, {class: 'border mt-3 text-black p-1 rounded'}) %><br>
          <%= button_tag(type: "submit") do %>
            <div class="<%= btn %> mt-10"> 追加</div>
          <% end %>
        <% end %>
    </div>
    <div class="my-auto h-full py-5 pl-5 bg-twibg rounded-md shadow-md xs:mb-5 md:mb-0">
        <%= form_with model: @maker, local: true do |f| %>
          <i class="fas fa-building text-pink-200 mr-1 text-xl text-center"></i>
          <%= f.text_field :name, placeholder: 'メーカー', class: 'w-1/2 bg-gray-700 text-gray-400 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300 placeholder-opacity-30 placeholder-white' %>
          <%= button_tag(type: "submit") do %>
            <div class="<%= btn %> mx-2"> 追加</div>
          <% end %>
        <% end %>
      <table class="table-auto">
        <thead>
          <tr></tr>
        </thead>
        <tbody>
          <% @makers.each do |maker| %>
            <tr>
              <td class="py-1">
                <%= link_to maker_path(maker), method: :delete, "data-confirm" => "削除しますか？", class: 'hover:opacity-75' do %>
                  <%= maker.name %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="h-full py-5 pl-5 bg-twibg rounded-md shadow-md md:mt-5 lg:mt-0 md:mr-auto md:ml-8 lg:mr-0 lg:ml-0">
        <%= form_with model: @category, local: true do |f| %>
          <i class="fas fa-keyboard mr-1 text-pink-200 text-xl"></i>
          <%= f.text_field :name, placeholder: 'カテゴリー', class: 'w-1/2 bg-gray-700 text-gray-400 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300 placeholder-opacity-30 placeholder-white' %>
          <%= button_tag(type: "submit") do %>
            <div class="<%= btn %> mx-2"> 追加</div>
          <% end %>
        <% end %>
      <table class="table-auto">
        <thead>
          <tr></tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td class="py-1">
                <%= link_to category_path(category), method: :delete, "data-confirm" => "削除しますか？", class: 'hover:opacity-75' do %>
                  <%= category.name %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="flex xs:flex-wrap xs:w-4/5 lg:w-full mx-auto justify-center py-10 rounded-md gap-5">
  <div class="shadow-lg bg-twibg xs:w-52 sm:w-72 rounded-md">
    <%= image_tag @item.image.variant(resize: "800x800^", gravity: "center", crop: "800x800+0+0").processed, class: 'w-full rounded' %>
    <div class="relative text-center py-4">
      <p class="text-gray-300 mt-3 p-2 font-bold"><%= @item.name %></p>
      <div id="average"><%= render '/items/average', average: @average, review_count: @review_count %></div>
      <span id="favorite_btn<%= @item.id %>"><%= render '/items/favorite_btn', item: @item %></span>
      <% if current_user.admin? %>
        <%= link_to edit_item_path(@item), class: 'text-gray-400 absolute bottom-2 right-2' do %>
          <i class="fas fa-edit hover:opacity-75"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <%= render 'form',item: @item, review: @review %>
  </div>
  <div class="px-10 flex flex-col gap-3 pb-5 pt-3 border-gray-600 border border-twibg rounded-md h-60">
    <p class="text-ratyyellow text-center font-semibold">評価別</p>
    <%= link_to item_path(@item,rate: "1") do %>
      <div class="flex justify-center hover:opacity-75" id="star11"></div>
    <% end %>
    <%= link_to item_path(@item,rate: "2") do %>
      <div class="flex justify-center hover:opacity-75" id="star12"></div>
    <% end %>
    <%= link_to item_path(@item,rate: "3") do %>
      <div class="flex justify-center hover:opacity-75" id="star13"></div>
    <% end %>
    <%= link_to item_path(@item,rate: "4") do %>
      <div class="flex justify-center hover:opacity-75" id="star14"></div>
    <% end %>
    <%= link_to item_path(@item,rate: "5") do %>
      <div class="flex justify-center hover:opacity-75" id="star15"></div>
    <% end %>
  </div>
</div>
<div class="scroll-list jscroll h-full pb-5">
  <div class="mt-5 mb-5 h-full reviews_ajax">
    <%= render '/items/reviews', reviews: @reviews %>
  </div>
  <div class=""><%= paginate @reviews %></div>
</div>


<script>
  $('#star11').empty();
  $('#star11').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: 1,
  });
  $('#star12').empty();
  $('#star12').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: 2,
  });
  $('#star13').empty();
  $('#star13').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: 3,
  });
  $('#star14').empty();
  $('#star14').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: 4,
  });
  $('#star15').empty();
  $('#star15').raty({
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: 5,
  });

</script>