config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users, skip: [:passwords], :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'filter' => 'searches#filter', as: 'filter'
  get 'user_search' =>'users#search', as: 'user_search'
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :favorites
    end
  end
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
  end
  resources :makers, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :maker
  belongs_to :category

  attr_accessor :average
  attr_accessor :amount


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def review_rate_average
    if reviews
      reviews.average(:rate).to_f.round(1)
    else
      0.0
    end
  end

  def review_amount
    if reviews
      reviews.count
    else
      0.0
    end
  end

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
    .category_like(search_params[:category_ids])
    .maker_like(search_params[:maker_ids])
  end

  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :category_like, -> (category) { where(category: category) if category.present? }
  scope :maker_like, -> (maker) { where(maker: maker) if maker.present? }
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_many :goods, dependent: :destroy


  validates :comment, presence: true, length: { maximum: 400 }
  validates :rate, presence: true

  def good_by?(user)
    goods.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :goods, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト',email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search,word)
    User.where("name LIKE?", "%#{word}%")
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :ensure_guest_user, only: [:create,:destroy]

  def create
    @review = Review.find(params[:item_id])
    good = current_user.goods.create(review_id: @review.id)
  end

  def destroy
    @review = Review.find(params[:item_id])
    good = current_user.goods.find_by(review_id: @review.id)
    good.destroy
  end

  private

  def ensure_guest_user
    if current_user.name == "ゲスト"
      redirect_to user_path(current_user), alert: '高評価機能の使用はユーザー登録が必要です。'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :ensure_guest_user
  before_action :ensure_user, only: [:edit, :update, :destroy]
  def create
    @item = Item.find(params[:item_id])
    review = current_user.reviews.new(review_params)
    review.item_id = @item.id
    @review_count = Review.where(item_id: @item.id).count
    review_count = Review.where(item_id: params[:item_id]).where(user_id: current_user.id).count
    if review.valid?
      if review_count < 1
       review.save
       @reviews = Review.where(item_id: @item.id)
       @average = @reviews.average(:rate)
       @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
       flash[:notice] = "レビューを投稿しました。"
       redirect_to request.referer
      else
        redirect_to request.referer, alert: "レビューの投稿は1度までです。"
      end
    else
      redirect_to request.referer, alert: "投稿に失敗しました。"
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to item_path(review.item), notice: "レビューを削除しました。"
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    if review.update(review_params)
      flash[:notice] = "レビューを編集しました。"
      redirect_to item_path(review.item)
    else
      @review = Review.find(params[:id])
      redirect_to request.referer, alert: "編集に失敗しました。"
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rate)
  end

  def ensure_guest_user
    if current_user.name == "ゲスト"
      redirect_to user_path(current_user), alert: 'レビュー機能の使用はユーザー登録が必要です。'
    end
  end

  def ensure_user
    review = Review.find(params[:id])
    unless (current_user == review.user) || current_user.admin
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tailwind_helper.rb
module TailwindHelper
  def btn
    'px-4 py-2 bg-gradient-to-r bg-twibg border border-gray-600 text-gray-300 hover:bg-gradient-to-r hover:from-purple-900 hover:to-pink-900 hover:text-gray-800 hover:border-twi duration-1000 rounded'
  end

  def btnd
    'ml-auto mt-auto px-4 py-2 bg-transparent text-red-400 border border-red-400 rounded hover:text-white hover:bg-red-400 duration-500'
  end

  def form
    'bg-twibg text-gray-400 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_edit_rate.html.erb
<%= form_with model: review, url: item_review_path, local: true do |f| %>
  <%= f.label :レビュー内容, class: 'text-gray-400' %>
  <%= f.text_area :comment,rows: 8, class: 'bg-gray-700 text-gray-200 text-sm focus:ring-4 focus:ring-purple-400 duration-300 rounded-md block xs:w-72 md:w-96 p-2 mt-2' %><br>
  <%= f.label :評価, class: 'text-gray-400' %>
  <div class="flex justify-center mb-5" id="edit-rate<%= review.id %>"></div>
  <script>
  $('#edit-rate<%= review.id %>').empty();
    $('#edit-rate<%= review.id %>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      half      : false,
      score: <%= review.rate %>,
      scoreName: 'review[rate]',
    });
  </script>
    <% if current_user.admin? || current_user == review.user %>
      <%= button_tag(type: "submit") do %>
        <div class="<%= btn %> mx-1">変更</div>
      <% end %>
      <%= link_to item_review_path(review),method: :delete, "data-confirm" => "本当に削除しますか？" do %>
        <button class="<%= btnd %> mx-1">削除</button>
      <% end %>
    <% end %>
<% end %>

app/views/reviews/create.js.erb
<!--$('.reviews_ajax').html("<%#= j(render '/items/reviews', reviews: @reviews) %>");-->
<!--$('textarea').val('');-->
<!--$('#average').html("<%#= j(render '/items/average', average: @average, review_count: @review_count) %>");-->
<!--$('#flash').html("<%#= j(render '/layouts/flash') %>");-->
<!--$('#star1').empty();-->
<!--$('#star1').raty({-->
<!--  size     : 36,-->
<!--  starOff:  '<%#= asset_path('star-off.png') %>',-->
<!--  starOn: '<%#= asset_path('star-on.png') %>',-->
<!--  starHalf: '<%#= asset_path('star-half.png') %>',-->
<!--  scoreName: 'review[rate]',-->
<!--  half: false,-->
<!--});-->

app/views/reviews/edit.html.erb
<div class="container mt-5 mx-auto">
  <div class="grid">
    <div class="mx-auto">
      <div class="text-center">
        <%= render 'edit_rate', review: @review %>
      </div>
    </div>
  </div>
</div>