config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users, skip: [:passwords], :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'filter' => 'searches#filter', as: 'filter'
  get 'user_search' =>'users#search', as: 'user_search'
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
     get :favorites
    end
  end
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :edit, :update, :destroy] do
      resource :goods, only: [:create, :destroy]
    end
  end
  resources :makers, only: [:create, :destroy]
  resources :categories, only: [:create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :maker
  belongs_to :category

  attr_accessor :average
  attr_accessor :amount


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def review_rate_average
    if reviews
      reviews.average(:rate).to_f.round(1)
    else
      0.0
    end
  end

  def review_amount
    if reviews
      reviews.count
    else
      0.0
    end
  end

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
    .category_like(search_params[:category_ids])
    .maker_like(search_params[:maker_ids])
  end

  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :category_like, -> (category) { where(category: category) if category.present? }
  scope :maker_like, -> (maker) { where(maker: maker) if maker.present? }
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_many :goods, dependent: :destroy


  validates :comment, presence: true, length: { maximum: 400 }
  validates :rate, presence: true

  def good_by?(user)
    goods.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :goods, dependent: :destroy

  validates :name, uniqueness: true, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト',email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search,word)
    User.where("name LIKE?", "%#{word}%")
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :ensure_guest_user, only: [:create,:destroy]

  def create
    @review = Review.find(params[:item_id])
    good = current_user.goods.create(review_id: @review.id)
  end

  def destroy
    @review = Review.find(params[:item_id])
    good = current_user.goods.find_by(review_id: @review.id)
    good.destroy
  end

  private

  def ensure_guest_user
    if current_user.name == "ゲスト"
      redirect_to user_path(current_user), alert: '高評価機能の使用はユーザー登録が必要です。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tailwind_helper.rb
module TailwindHelper
  def btn
    'px-4 py-2 bg-gradient-to-r bg-twibg border border-gray-600 text-gray-300 hover:bg-gradient-to-r hover:from-purple-900 hover:to-pink-900 hover:text-gray-800 hover:border-twi duration-1000 rounded'
  end

  def btnd
    'ml-auto mt-auto px-4 py-2 bg-transparent text-red-400 border border-red-400 rounded hover:text-white hover:bg-red-400 duration-500'
  end

  def form
    'bg-twibg text-gray-400 rounded text-sm focus:ring-4 focus:ring-purple-400 p-2 duration-300'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% if key == "notice" %>
  <div class="pt-2 w-1/2 mx-auto bg-gradient-to-r from-purple-400 to-pink-300 rounded-b contents" id="notice_message">
    <%= content_tag(:p, class: "flex p-4 bg-gradient-to-r from-purple-200 to-pink-200 w-full mx-auto rounded-b shadow-md relative items-center") do %>
      <span class="pt-3"></span>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 flex-shrink-0 w-5 h-5 text-purple-800" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span class="text-purple-800 pl-3"><%= value %></span>
      <button class="mt-10" id="notice_close">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 absolute top-6 right-6 hover:opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
      </button>
    <% end %>
  </div>
  <% elsif key == "alert" %>
    <div id="alert_message" class="contents">
      <%= content_tag(:p, class: "flex p-4 mb-4 border-t-4 border-red-500 bg-red-100 relative items-center mx-auto rounded-b shadow-md") do %>
        <span class="pt-3"></span>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 flex-shrink-0 w-5 h-5 text-red-700 text-sm" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span class="text-red-700 pl-3"><%= value %></span>
        <button class="mt-10" id="alert_close">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 absolute top-6 right-6 hover:opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
        </button>
      <% end %>
    </div>
  <% end %>
<% end %>

<script>
  $(function(){
    $('#notice_close').on('click',function(){
       $('#notice_message').fadeOut();
     });
  });
  $(function(){
    $('#alert_close').on('click',function(){
       $('#alert_message').fadeOut();
     });
  });
</script>

app/views/layouts/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-gradient-to-tr from-purple-900 to-pink-900 sticky top-0 z-10 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <%= link_to "addevice", items_path, class: 'font-extrabold text-xl tracking-tight italic hover:text-pink-700 duration-300' %>
  </div>
  <div class="text-sm">
    <% if user_signed_in? && current_user.admin? %>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to current_user do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to users_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to filter_path, data: {"turbolinks" => false} do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to new_item_path do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
        <% end %>
      </div>
    <% elsif user_signed_in? %>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to current_user do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to filter_path, data: {"turbolinks" => false} do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
        <% end %>
      </div>
      <div class="inline-block mt-4 text-white hover:text-pink-700 duration-300 mr-4">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Addevice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  </head>

  <body class="bg-twi font-sans">
    <%= render '/layouts/header' %>
   <div id="flash"><%= render '/layouts/flash' %></div>
    <%= yield %>
  </body>
</html>